name: Build and Deploy Doxygen Documentation

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install doxygen graphviz -y

      - name: Clean repository
        run: |
          git reset --hard
          git clean -fdx

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          
